namespace: google
name: gcp
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collections/google.gcp.git
documentation: null
homepage: null
issues: null
